name: Task

on:
  workflow_dispatch:

jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: "${{ secrets.T1_REPO }}"
          ref: "${{ secrets.T1_REPO_REF }}"
          token: "${{ secrets.T1_REPO_TOKEN }}"
      - run: ls
