name: Task

on:
  workflow_dispatch:

jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          repository: "${{ secrets.T1_REPO }}"
          ref: "${{ secrets.T1_REPO_REF }}"
          token: "${{ secrets.T1_REPO_TOKEN }}"
      - uses: oven-sh/setup-bun@v2
      - run: bun install && bun run index.ts
